name: Deploy to FTP

on: [push]

jobs:
  ftp-deploy:
    name: Deploy HTML file to FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp.wowdruk.be }}
        username: ${{ secrets.cal@wowdruk.be }}
        password: ${{ secrets.wowdruk }}
        local-dir: "."
        server-dir: "path/to/your/remote/directory"
